### ISSUE TITLE
Функция iFeel может управляться только с пульта. 

### ISSUE THREAD

**Issue by Brokly** [GrKoR/AUX_HVAC_Protocol#1]
Никакими посылками не удалось изменить состояние iFeel. 

Бит 3, Байта 7, тела пакета - iFeel

Кусок лога, где осуществляется попытка изменения бита iFeel
[=>] [BB 00 06 80 00 00 0F 00] 01 01 97 20 00 40 00 20 00 00 20 00 10 00 00 [66 FD]
[<=] [BB 00 07 00 00 00 0F 00] 01 11 97 20 00 40 00 28 00 00 20 00 10 00 00 [66 65]  

Переключение возможно только с пульта.

**Comment by GrKoR** [comment]
Хотел вносить исправления в доку, но заметил странное.

Нужный байт команды выделен минусами. Описание битов этого байта [тут](https://github.com/GrKoR/AUX_HVAC_Protocol#packet_cmd_11_b15). 

Команда кондиционеру:
> [=>] [BB 00 06 80 00 00 0F 00] 01 01 97 20 00 40 00 -20- 00 00 20 00 10 00 00 [66 FD]

Если её расшифровать, то в этом байте нет попытки включить iFeel. Байт равен `0b 0010 0000`. Это работа сплита в режиме COOL. Включения бита **iFL** не происходило.

А вот обратный пакет с информацией о режиме:
> [BB 00 07 00 00 00 0F 00] 01 11 97 20 00 40 00 -28- 00 00 20 00 10 00 00 [66 65]

Тут значение байта уже `0b 0010 1000`. То есть бит **iFL** установлен в `1`. А значит включение функции iFeel произошло.

Ситуация не понятна. Нужно пояснение @Brokly

**Comment by Brokly** [comment]
Это было не включение, а выключение. 
20 - попытка снять бит
28 -  кондей отвечает по прежнему, не измененным значением

**Comment by GrKoR** [comment]
Ясно! Спасибо
