### ISSUE TITLE
Бит 0 Байт 10 (status) малого пакета

### ISSUE THREAD

**Issue by Brokly** [GrKoR/AUX_HVAC_Protocol#2]
Бит 0 Байт 10 (status) малого пакета (HEALTH ERROR/STATUS)

У меня всегда устанавливается сам, при переключении бита HEALTH  (Бит 1 Байт 10 (status)) в единицу и сам сбрасывается при сбросе HEALTH. Кондиционер Energolux Bern, по мануалу имеет ионизатор, сам я его не нашел. Каких либо отверстий, обычных для кондеев с ионизатором у моего кондиционера нет. Допускаю отсутствие ионизатора как такового. Смысл бита, в конечном итоге, не ясен. Применение не понятно.

**Comment by GrKoR** [comment]
связано с: issue #5
