### ISSUE TITLE
Смешно, но диапазон температур шире :)

### ISSUE THREAD

**Issue by Brokly** [GrKoR/AUX_HVAC_Protocol#3]
С помощью свиста можно установить нижнюю температуру ниже 16 :)) Верхнюю просто не тестировал.

**Comment by GrKoR** [comment]
Вообще не понятно, как устанавливать ограничения) Вроде на одной железке все проверишь, а на другой всё иначе 🙂

**Comment by GrKoR** [comment]
[для себя] проверить, как инициализируются значения минимума и максимума температур

**Comment by GrKoR** [comment]
Brokly: Короче это мой косяк. Просто не правильно выводил данные в лог.

**Comment by GrKoR** [comment]
Поспешил закрыть ишью. Надо же посмотреть, что там с установкой температуры ниже 16 и выше 32

**Comment by GrKoR** [comment]
Создал соответствующий ишью для компонента. Тут можно закрывать
