### ISSUE TITLE
Странная температура это температура компрессора.

### ISSUE THREAD

**Issue by Brokly** [GrKoR/AUX_HVAC_Protocol#4]
Сравнил графики температур . Показания из протокола (большой пакет) и физического датчика установленного на компрессоре. Совпадают.

**Comment by GrKoR** [comment]
Это температура датчика, непосредственно установленного на компрессоре внутри наружного блока? Фотки есть?) можешь сюда сбросить?

**Comment by GrKoR** [comment]
![image](https://user-images.githubusercontent.com/57137862/170863944-32319ec7-d14b-4125-8217-544411702f24.jpeg)

Brokly: Верхний график "странная температура", нижний - лог с термометра укрепленного на компрессоре :)
